name: waste2worth
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4
  image: ^4.1.3
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4
  google_fonts: ^6.2.0
  carousel_slider:
      git:
        url: https://github.com/serenader2014/flutter_carousel_slider
        ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

